### PR TITLE
Fixed struct parsing expression

### PR DESCRIPTION
**Pull request by damon-kwok**
At moment, a warning is raised when parsing a struct, this PR fixes it.

### CODE REVIEW

**Comment by SeanTAllen** [comment]
@damon-kwok is there any way to have automated tests for ctags? Accepting PRs is difficult without automated tests. Given there are currently no automated tests, please include how this should be tested so that the problem can be seen prior to this change and what is fixed.

That doesn't help with finding regressions (like an automated test suite would), but its better than nothing right now.

**Comment by damon-kwok** [comment]
https://github.com/ponylang/pony-ctags/pull/2/files
This is a bug I introduced in #2

**Comment by SeanTAllen** [comment]
@damon-kwok what is the bug and how can this be tested?

**Comment by damon-kwok** [comment]
@SeanTAllen 
See line:9
old: --regex-pony=/^[ \t]*struct[ \t]+([a-zA-Z0-9_]+)/\1/p,struct/
new --regex-pony=/^[ \t]*struct[ \t]+([a-zA-Z0-9_]+)/\1/s,struct/

`p,struct` is a error, `s,struct` is correct.

**Comment by SeanTAllen** [comment]
@damon-kwok I understand the difference. What is impact of this "error"? Does it still correctly handle the tag?

**Comment by damon-kwok** [comment]
Yes,  p is already occupied by promitive, it output:
> ctags: Warning: Don't reuse the kind letter `p' in a language pony (old: "primitive", new: "struct")

Screenshot from 2020-07-04 09-26-58

**Comment by SeanTAllen** [comment]
Gotcha

**Pull request merged**
